Added frozen food timeslot
bula21/mova21-orca pull request #255
Opened 2022-06-26 15:11 UTC by jimmylevell

2022-06-27 17:20 UTC, diegosteiner requested changes

2022-06-27 17:20 UTC, diegosteiner commented on app/helpers/frozen_food_timeslot_helper.rb
> +            timeslot = "not possible to calculate time"
Schöner wäre noch hier eine Guard-clause zu nutzen:

```
def frozen_food_timeslot(timeslot)
        timeslot.squish!
        matches = timeslot.match(/((\d?\d).(\d?\d))-((\d?\d).(\d?\d))/)

        return "not possible to calculate time" unless matches

        timeslot_1 = (Time.parse(matches[1].gsub(".", ":")) - 5.hours).strftime("%H.%M") 
        timeslot_2 = (Time.parse(matches[4].gsub(".", ":")) - 5.hours).strftime("%H.%M") 

        return timeslot_1 + "-" + timeslot_2
end
```

dann könnte man das noch DRY-er machen:
```
def frozen_food_timeslot(timeslot)
        timeslot.squish!
        matches = timeslot.match(/((\d?\d).(\d?\d))-((\d?\d).(\d?\d))/)

        return "not possible to calculate time" unless matches

        [matches[1], matches[4]].map { |time| Time.parse(time.gsub(".", ":")) - 5.hours).strftime("%H.%M") }.join('-')
end
```

dann könnte man noch squish vor den match nehmen:

```
def frozen_food_timeslot(timeslot)
        matches = timeslot.squish.match(/((\d?\d).(\d?\d))-((\d?\d).(\d?\d))/)

        return "not possible to calculate time" unless matches

        [matches[1], matches[4]].map { |time| Time.parse(time.gsub(".", ":")) - 5.hours).strftime("%H.%M") }.join('-')
end
```

Und allenfalls müsste der Fehlerfall noch übersetzt werden

2022-06-27 17:20 UTC, diegosteiner commented on app/helpers/frozen_food_timeslot_helper.rb
> +    require "time"
Das braucht es nicht, oder?

2022-06-27 17:21 UTC, diegosteiner commented
Unbedingt vor dem commit noch `bin/check` ausführen, das fixt die meisten Linting-Fehler automatisch.

2022-06-27 18:44 UTC, jimmylevell commented on app/helpers/frozen_food_timeslot_helper.rb
> +    require "time"
Meinst du hier Zeile 1?

2022-06-27 18:44 UTC, jimmylevell commented on app/helpers/frozen_food_timeslot_helper.rb
> +            timeslot = "not possible to calculate time"
Danke!! Werde die trockenste Version umsetzen :)

2022-06-27 18:48 UTC, jimmylevell commented on app/helpers/frozen_food_timeslot_helper.rb
> +    require "time"
Dachte da wir Time benötigen, muss ich es importieren. 
Funktioniert aber auch ohne

2022-06-27 18:59 UTC, jimmylevell commented
Ist die Fehlermeldung aussagekräfitg? Soll ich mit mailto: verlinken?

2022-06-29 07:40 UTC, diegosteiner approved these changes

2022-06-29 08:17 UTC, merged